/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AssaultWindow.java
 *
 * Created on Apr 18, 2010, 10:56:33 PM
 */
package assault.defunct;

import assault.game.loading.ResourcePreloader;
import assault.game.Player;
import assault.game.display.GameArea;
import assault.game.display.StatusDisplayMenu;
import assault.game.display.CommandDispatchMenu;
import assault.game.gameObjects.AGroup;
import assault.game.gameObjects.AUnit;
import assault.game.loading.resourceHolders.ResourceException;
import assault.game.loading.resourceHolders.UnitResourceHolder;
import java.awt.Color;

/**
 *
 * @author matt
 */
public final class AGameViewer extends javax.swing.JFrame {
	
	/*private final Player p1;
	private final Player p2;
	private final GameArea ampMainPanel;
	private final ResourcePreloader rp;*/

	/** Creates new form AssaultWindow */
	/*public AGameViewer() {
		super();
		initComponents();
		//this is used as a temp proxy to avoid annoying casts to GameArea
		ampMainPanel = (GameArea) lPMainPanel;
		String[] mods = {
			"default",};
		p1 = new Player(Color.red);
		p2 = new Player(Color.orange);
		rp = new ResourcePreloader(mods, getAMP());
		new Thread(new Runnable() {

			@Override
			public void run() {
				synchronized (this) {
					try {
						wait(3000);
					} catch (InterruptedException ex) {
					}
				}
				rp.start();
				try {
					AUnit en2 = new AUnit(105, 300, rp.getModUnitByName("default","SimpleUnit2"), p1);
					ampMainPanel.add(en2);

					AUnit b1 = new AUnit(505, 100, rp.getModUnitByName("default","SimpleBuilding"), p1);
					ampMainPanel.add(b1);
					
					AUnit e1 = new AUnit(105, 400, rp.getModUnitByName("default","SimpleUnit2"), p2);
					ampMainPanel.add(e1);
					
					AUnit e2 = new AUnit(505, 200, rp.getModUnitByName("default","SimpleBuilding"), p2);
					ampMainPanel.add(e2);

					AUnit e3 = new AUnit(605, 50, rp.getModUnitByName("default","SimpleUnit"), p2);
					ampMainPanel.add(e3);
					
					AUnit u1 = new AUnit(605, 100, rp.getModUnitByName("default","SimpleUnit"), p1);
					ampMainPanel.add(u1);
					AUnit u2 = new AUnit(705, 100, rp.getModUnitByName("default","SimpleUnit2"), p1);
					ampMainPanel.add(u2);
					AUnit u3 = new AUnit(805, 100, rp.getModUnitByName("default","SimpleUnit"), p1);
					ampMainPanel.add(u3);
					AUnit[] gu1 = {u1, u2, u3};
					AGroup g1 = new AGroup(gu1, p1);
					ampMainPanel.add(g1);
					
					UnitResourceHolder su1 = rp.getModUnitByName("default","SimpleUnit");
					for (int i = 0; i <= 6; i++) {
						ampMainPanel.add(new AUnit((i * 58) + 100, 200, su1, p1));
					}
					
					UnitResourceHolder su2 = rp.getModUnitByName("default","SimpleUnit2");
					for (int i = 0; i <= 6; i++) {
						ampMainPanel.add(new AUnit((i * 65) + 100, 500, su2, p2));
					}

				} catch (ResourceException ex) {
					rp.addError(ex);
				}
				synchronized (this) {
					try {
						wait(2000);
					} catch (InterruptedException ex) {
					}
					lPMainPanel.remove(rp);
				}
			}
		}).start();
	}*/

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	/*@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SDMScrollPane = new javax.swing.JScrollPane();
        statusDisplayMenu = new assault.game.display.StatusDisplayMenu();
        mainScrollPane = new javax.swing.JScrollPane();
        lPMainPanel = new assault.game.display.GameArea();
        jButton1 = new javax.swing.JButton();
        CDMScrollPane = new javax.swing.JScrollPane();
        commandDispatchMenu = new assault.game.display.CommandDispatchMenu();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Assault");
        setName("AssultFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1168, 661));

        SDMScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SDMScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        statusDisplayMenu.setLayout(null);
        SDMScrollPane.setViewportView(statusDisplayMenu);

        lPMainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lPMainPanel.setDoubleBuffered(true);
        lPMainPanel.setSize(new java.awt.Dimension(903, 641));
        mainScrollPane.setViewportView(lPMainPanel);

        jButton1.setText("Shoot");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CDMScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        CDMScrollPane.setSize(((CommandDispatchMenu)commandDispatchMenu).refreshSize());

        commandDispatchMenu.setSize(((CommandDispatchMenu)commandDispatchMenu).refreshSize()
        );
        commandDispatchMenu.setLayout(null);
        CDMScrollPane.setViewportView(commandDispatchMenu);

        jButton2.setText("ACDM.repaint()");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(mainScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 903, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(19, 19, 19)
                                .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 167, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(38, 38, 38)
                                .add(jButton2))))
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, CDMScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, SDMScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 235, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(mainScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 641, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(SDMScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 293, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(34, 34, 34)
                        .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(36, 36, 36)
                        .add(jButton2)
                        .add(18, 18, 18)
                        .add(CDMScrollPane)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
*/
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		
	}//GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		//getACDM().repaint();
	}//GEN-LAST:event_jButton2ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {

			@Override
			public void run() {
				new AGameViewer().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane CDMScrollPane;
    private javax.swing.JScrollPane SDMScrollPane;
    private javax.swing.JPanel commandDispatchMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLayeredPane lPMainPanel;
    private javax.swing.JScrollPane mainScrollPane;
    private javax.swing.JPanel statusDisplayMenu;
    // End of variables declaration//GEN-END:variables

	/*public StatusDisplayMenu getASDM() {
		return (StatusDisplayMenu) statusDisplayMenu;
	}

	public CommandDispatchMenu getACDM() {
		return (CommandDispatchMenu) commandDispatchMenu;
	}

	public GameArea getAMP() {
		return (GameArea) lPMainPanel;
	}

	public ResourcePreloader getRP() {
		return rp;
	}*/
}
